### ISSUE TITLE
Magnifying glass icon for "Search for Articles" from home page is displaying on Sign in/Sign up page popup 

### ISSUE THREAD

**Issue by monicaallcures** [EtheriumTechnologies/React-All-Cures#21]
Steps to reproduce:

1. Home page > Click on Sign in/Sign up link > on Sign in - Create New Account popup notice the magnifying glass icon is displaying on word "Account" from the page behind

![Screenshot from 2021-08-23 15-21-03](https://user-images.githubusercontent.com/89062641/130428249-00e1224c-0bf6-46d7-b1ad-6418edb9da53.png)

**Comment by anilraina001** [comment]
Not able to reproduce it.

**Comment by ayush-pradhan** [comment]
Fixed.

**Comment by monicaallcures** [comment]
Fixed and Validated.
